iterate tests, and _assert_not

diff --git a/tests/lib b/tests/lib
--- a/tests/lib
+++ b/tests/lib
@@ -21,12 +21,22 @@ _assert_variable(){
 	_assert [ ! -z "$STR" ]
 }
 
+_assert_not(){
+	if [ $# -ne 0 ]; then
+		err "$@"
+		"$@" > /dev/null
+		if [ $? -eq 0 ]; then
+			err "ERROR assertion failed: NOT $@"
+		fi
+	fi
+}
+
 _assert(){
 	if [ $# -ne 0 ]; then
 		err "$@"
 		"$@" 2> /dev/null
 		if [ $? -ne 0 ]; then
-			err "Error assertion failed: $@"
+			err "ERROR assertion failed: $@"
 		fi
 	fi
 }
